language: go
env:
  matrix:
  - GO15VENDOREXPERIMENT=1
branches:
  only:
  - openshift-all2
  - "/^v(?:[0-9]+\\.){2}[0-9]+.*$/"
cache:
  directories:
  - "$GOPATH/src/github.com/helm/helm/vendor"
go:
  - 1.5.1
install:
  - cd $HOME/gopath/src/github.com/
  - mkdir -p helm
  - cd helm
  - rm -rf helm
  - mv $HOME/gopath/src/github.com/fabric8io/helm $HOME/gopath/src/github.com/helm
  - cd helm
  - pwd
  - wget "https://github.com/Masterminds/glide/releases/download/0.7.2/glide-0.7.2-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-0.7.2-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH" GLIDE_HOME="$HOME/.glide"
  - go get github.com/golang/lint/golint
script: make bootstrap build test test-charts
before_deploy: make bootstrap-dist dist prep-bintray-json
deploy:
- provider: bintray
  file: _scripts/ci/bintray-ci.json
  user: fabric8io
  key:
    secure: RrpzcbCW8lVhrSrjNlW7wdmCLcpTrCp/q1XnD4JqoaVrHltN5ZPUKv4/yrGry4vJezgzldlFl5cdjUOoMFYD6NcfkhIP30u1c9RvsPuCewbHSsDuunj9iQ+UDjhl5oNxuuqeXsAOGvv4uQeaIaaXFb/tv70FLW8Gxoz9m1nM7Kx5FhswKlYsh7+5WbXaTqz6ZwHzpRvJs9SMq+IP9cE78bZMgAkv1arh5dExMec/6SOkNFfESzJy1YwPMwZ0wFLEM1LtgeuHhoVPjqCssY1B2OvYU+/tkBFzMFoiruvDtcVTSkBMiAQSBo+MnZf+Pm2jPwnby0kM1YLDboSU7lG9NjUXqxLJhZzUm4p8Jp8ROu//EtyW97XseZQ+Y4xFiNfA1lYxmwF8pP8Vxxqx/OJPPRSUqJlMCstyXiEpkcGavhRnRLyxLT+Q1aDMWlt+6FK1WLrdSNIsU2j2Ehhz1z1DGletpshrZ9JwndYZBahKQ4yFb4as4VjIWdQNCgTefawXjbC60rDjWynuPXx5Fex0Uu1TdXrYeCVQ5tiXaw4iob/qnaIwn9kkXKhELbNGCtY7HRbEdBsKLc2EYX16BT0/zo1dnVauPruALhA+miDHnlg1XBjtUS9GutVE9RENRrRF5W4uM3UJGuNRrzA96lrno08q1pYN8wD2yrS6DVy6vQg=
  on:
    all_branches: true
    condition: "${TRAVIS_PULL_REQUEST} == false"
